name: Unit Tests

on:
  workflow_dispatch:

  push:
    paths:
      - 'auth_server/**'
      - 'tests/**'
      - '.github/**'

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install && poetry run pytest
        env:
            PAPERMERGE__SECURITY__SECRET_KEY: ${{ secrets.security__secret_key }}
